/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DownloadBar: typeof import('./src/components/download/DownloadBar.vue')['default']
    DownloaderPane: typeof import('./src/components/DownloaderPane.vue')['default']
    DownloadPane: typeof import('./src/components/download/DownloadPane.vue')['default']
    DownloadSearchBar: typeof import('./src/components/download/DownloadSearchBar.vue')['default']
    DownloadTree: typeof import('./src/components/download/DownloadTree.vue')['default']
    ExportBar: typeof import('./src/components/export/ExportBar.vue')['default']
    ExportPane: typeof import('./src/components/export/ExportPane.vue')['default']
    ExportRefreshButton: typeof import('./src/components/export/ExportRefreshButton.vue')['default']
    ExportTree: typeof import('./src/components/export/ExportTree.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NFlex: typeof import('naive-ui')['NFlex']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NProgress: typeof import('naive-ui')['NProgress']
    NResult: typeof import('naive-ui')['NResult']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NText: typeof import('naive-ui')['NText']
    SettingsPane: typeof import('./src/components/settings/SettingsPane.vue')['default']
  }
}
