/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CacheDirectoryInput: typeof import('./src/components/settings/CacheDirectoryInput.vue')['default']
    DownloadButton: typeof import('./src/components/download/DownloadButton.vue')['default']
    DownloadList: typeof import('./src/components/download/DownloadList.vue')['default']
    DownloadPane: typeof import('./src/components/download/DownloadPane.vue')['default']
    DownloadProgress: typeof import('./src/components/download/DownloadProgress.vue')['default']
    DownloadSearchBar: typeof import('./src/components/download/DownloadSearchBar.vue')['default']
    DownloadSearchList: typeof import('./src/components/download/DownloadSearchList.vue')['default']
    DownloadTree: typeof import('./src/components/download/DownloadTree.vue')['default']
    ExportBar: typeof import('./src/components/export/ExportBar.vue')['default']
    ExportDirectoryInput: typeof import('./src/components/settings/ExportDirectoryInput.vue')['default']
    ExportPane: typeof import('./src/components/export/ExportPane.vue')['default']
    ExportRefreshButton: typeof import('./src/components/export/ExportRefreshButton.vue')['default']
    ExportTree: typeof import('./src/components/export/ExportTree.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NH3: typeof import('naive-ui')['NH3']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPagination: typeof import('naive-ui')['NPagination']
    NPopover: typeof import('naive-ui')['NPopover']
    NProgress: typeof import('naive-ui')['NProgress']
    NResult: typeof import('naive-ui')['NResult']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NText: typeof import('naive-ui')['NText']
    SettingsPane: typeof import('./src/components/settings/SettingsPane.vue')['default']
  }
}
