// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ComicInfoModel() {
  return window['go']['api']['DownloadApi']['ComicInfoModel']();
}

export function DownloadChapter(arg1, arg2, arg3, arg4) {
  return window['go']['api']['DownloadApi']['DownloadChapter'](arg1, arg2, arg3, arg4);
}

export function SearchComicInfo(arg1, arg2, arg3) {
  return window['go']['api']['DownloadApi']['SearchComicInfo'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['api']['DownloadApi']['Startup'](arg1);
}
