// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ComicInfoModel() {
  return window['go']['api']['DownloadApi']['ComicInfoModel']();
}

export function ComicSearchResultModel() {
  return window['go']['api']['DownloadApi']['ComicSearchResultModel']();
}

export function DownloadChapter(arg1, arg2, arg3, arg4) {
  return window['go']['api']['DownloadApi']['DownloadChapter'](arg1, arg2, arg3, arg4);
}

export function SearchComicById(arg1, arg2, arg3) {
  return window['go']['api']['DownloadApi']['SearchComicById'](arg1, arg2, arg3);
}

export function SearchComicByKeyword(arg1, arg2) {
  return window['go']['api']['DownloadApi']['SearchComicByKeyword'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['api']['DownloadApi']['Startup'](arg1);
}
