// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {search} from '../models';
import {types} from '../models';
import {context} from '../models';

export function ComicInfoModel():Promise<search.ComicInfo>;

export function DownloadChapter(arg1:string,arg2:string,arg3:number,arg4:string):Promise<types.Response>;

export function SearchComicInfo(arg1:string,arg2:string,arg3:string):Promise<types.Response>;

export function Startup(arg1:context.Context):Promise<void>;
