// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {export_pdf} from '../models';
import {types} from '../models';
import {context} from '../models';

export function CreatePdfs(arg1:export_pdf.CreatePdfsRequest):Promise<types.Response>;

export function MergePdfs(arg1:string,arg2:string):Promise<types.Response>;

export function ScanCacheDir(arg1:string,arg2:number):Promise<types.Response>;

export function Startup(arg1:context.Context):Promise<void>;

export function TreeOptionModel():Promise<types.TreeNode>;
