// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePdfs(arg1) {
  return window['go']['api']['ExportApi']['CreatePdfs'](arg1);
}

export function MergePdfs(arg1, arg2) {
  return window['go']['api']['ExportApi']['MergePdfs'](arg1, arg2);
}

export function ScanCacheDir(arg1, arg2, arg3) {
  return window['go']['api']['ExportApi']['ScanCacheDir'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['api']['ExportApi']['Startup'](arg1);
}

export function TreeOptionModel() {
  return window['go']['api']['ExportApi']['TreeOptionModel']();
}
