// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAbsPath(arg1) {
  return window['go']['api']['PathApi']['GetAbsPath'](arg1);
}

export function GetRelPath(arg1, arg2) {
  return window['go']['api']['PathApi']['GetRelPath'](arg1, arg2);
}

export function Join(arg1) {
  return window['go']['api']['PathApi']['Join'](arg1);
}

export function MkDirAll(arg1) {
  return window['go']['api']['PathApi']['MkDirAll'](arg1);
}

export function PathExists(arg1) {
  return window['go']['api']['PathApi']['PathExists'](arg1);
}

export function Startup(arg1) {
  return window['go']['api']['PathApi']['Startup'](arg1);
}

export function UserDownloadPath() {
  return window['go']['api']['PathApi']['UserDownloadPath']();
}
