// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetAbsPath(arg1:string):Promise<string>;

export function GetRelPath(arg1:string,arg2:string):Promise<string>;

export function Join(arg1:Array<any>):Promise<string>;

export function MkDirAll(arg1:string):Promise<void>;

export function PathExists(arg1:string):Promise<boolean>;

export function Startup(arg1:context.Context):Promise<void>;

export function UserDownloadPath():Promise<string>;
