// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDirectory(arg1) {
  return window['go']['api']['SettingsApi']['ChooseDirectory'](arg1);
}

export function Startup(arg1) {
  return window['go']['api']['SettingsApi']['Startup'](arg1);
}
