// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCpuNum() {
  return window['go']['api']['UtilsApi']['GetCpuNum']();
}

export function GetUserDownloadPath() {
  return window['go']['api']['UtilsApi']['GetUserDownloadPath']();
}

export function GetUserProxy() {
  return window['go']['api']['UtilsApi']['GetUserProxy']();
}

export function Startup(arg1) {
  return window['go']['api']['UtilsApi']['Startup'](arg1);
}
